### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by IanButterworth** [Gnimuc/Redux.jl#3]
+1 for letting this package out into the real world

**Comment by Gnimuc** [comment]
This package is still WIP and I'm still experimenting features like async actions, undo-redo. Redux is a javascript framework, so it may take a bit of time to figure out a good Julian implementation. But I agree we can register a 0.1.0 version to let this package get more exposure. :)

**Comment by IanButterworth** [comment]
Great. I'm going to start trying it out and will issue/PR any ideas
